# Generated by Django 5.2.9 on 2025-12-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('templates_eval', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['is_closed', 'start_date', 'end_date'], name='evaluations_is_clos_e1cbc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('frozen_position_code', models.CharField(max_length=8)),
                ('frozen_position_name', models.CharField(max_length=160)),
                ('final_score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='org.employee')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_made', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.evaluationperiod')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates_eval.templateitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['period', 'status'], name='evaluations_period__0999c3_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator', 'period'], name='evaluations_evaluat_93454a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('employee', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('evaluation', 'template_item')},
        ),
    ]
