# Generated by Django 5.2.9 on 2025-12-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluation_template'),
        ('templates_eval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yes_no', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='templates_eval.templatequestion')),
            ],
            options={
                'indexes': [models.Index(fields=['evaluation', 'question'], name='evaluations_evaluat_2e5922_idx')],
                'unique_together': {('evaluation', 'question')},
            },
        ),
    ]
